customer/urls.py
from . import views
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

app_name = 'customer'

urlpatterns = [
    path('', views.portal, name='customerportal'),

    # Auth
    path('signup/', views.signupuser, name='signupuser'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jasservices/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from home import views

urlpatterns = [
    # Admin
    path('admin/', admin.site.urls),

    # Home
    path('', views.home, name='home'),
    path('insurance/', views.insurance, name='insurance'),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('career/', views.career, name='career'),
    path('loan/', views.loan, name='loan'),
    path('property/', views.property, name='property'),
    path('suggestion/', views.suggestion, name='suggestion'),
    path('sendemail/', views.sendemail, name='sendemail'),
    # User
    #path('customer/', include('customer.urls', namespace="customer")),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customer/models.py
from django.db import models
from django.contrib.auth.models import User


class Customer(models.Model):
    objects = None
    title = models.CharField(max_length=100)
    memo = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    datecompleted = models.DateTimeField(null=True, blank=True)
    important = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

home/models.py
from django.db import models


class Deals(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

customer/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
import datetime

from .Forms import CustomerForm
from .models import Customer
from django.utils import timezone

date = datetime.date.today()

def portal(request):
    return render(request, 'customer/customerportal.html',{"date": date})


def signupuser(request):
    if request.method == 'GET':
        return render(request, 'customer/signupuser.html', {'form': UserCreationForm(),"date": date})
    else:
        # Create a new user
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'], email=request.POST['email'])
                email = request.POST['email'].lower()
                r = User.objects.filter(email=email)
                if r.count()==0:
                    return render(request, 'customer/signupuser.html',
                                  {'error': 'Email already exists',"date": date})
                else:
                    user.save()
                    login(request, user)
                    return redirect('customer:info')

            except IntegrityError:
                return render(request, 'customer/signupuser.html',
                              {'error': 'This username has already been taken. Please choose a new Username'})
            except ValueError:
                return render(request, 'customer/signupuser.html',
                              {'error': 'Please enter valid username',"date": date})
        else:
            # tell the user the password didn't match
            return render(request, 'customer/signupuser.html', {'error': 'Passwords did not match'})

home/views.py
from django.shortcuts import render
import datetime
from .models import Deals
from django.core.mail import send_mail

date = datetime.date.today()

def home(request):
    deals = Deals.objects.all()
    n=0
    for deal in deals:
       n=n+1
    return render(request, 'home/home.html',{"date": date, 'deals':deals,'n':n})

def insurance(request):
    return render(request, 'home/insurance.html',{"date": date})

def property(request):
    return render(request, 'home/property.html',{"date": date})

def loan(request):
    return render(request, 'home/loan.html',{"date": date})

def aboutus(request):
    return render(request, 'home/aboutus.html',{"date": date})

def career(request):
    return render(request, 'home/career.html',{"date": date})

def suggestion(request):
    return render(request, 'home/suggestion.html',{"date": date})

def sendemail(request):
    send_mail('Hello this is trial','This automated message','sk2todos@gmail.com',['kharulswarupsk@gmail.com'], fail_silently=False)
    return render(request, 'home/sendemail.html',{"date": date})

customer/templates/customer/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
        <link rel="icon" type="image/png"  href="{% static 'customer/logo.jpeg' %}">
    <title> JAS Services</title>
</head>
<body>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">


<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="#"><img src="{% static 'customer/logo.jpeg' %}" width="30" height="30" class="d-inline-block align-top"><strong> JAS Services</strong></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        <li class="nav-item active"><a class="nav-link" href="#">Today, {{ date }} <span class="sr-only">(current)</span></a></li>
        </ul>
        <ul class="navbar-nav ml-auto">
        <li class="nav-item active"><a class="nav-link" href="{% url 'aboutus' %}">About Us <span class="sr-only">(current)</span></a></li>
	    <li class="nav-item dropdown"><a style="color:rgb(255,255,255);" class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">Services</a>
	    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'insurance' %}">Insurance</a>
                <a class="dropdown-item" href="{% url 'loan' %}">Loans</a>
                <a class="dropdown-item" href="{% url 'property' %}">Property</a>
            </div>
        <li class="nav-item dropdown"><a style="color:rgb(255,255,255);" class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Customer Portal</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'customer:signupuser' %}">Register</a>
                <a class="dropdown-item" href="{% url 'customer:loginuser' %}">Login</a>
                    <a class="dropdown-item" href="{% url 'complaint' %}">Complaint</a>
                    <a class="dropdown-item" href="{% url 'suggestion' %}">Suggestion</a>

            </div>
            <li class="nav-item active"><a class="nav-link" href="{% url 'career' %}">Careers<span class="sr-only">(current)</span></a></li>
            <li class="nav-item active"><a class="nav-link" href="{% url 'career' %}">Contact Us<span class="sr-only">(current)</span></a></li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a href="#" onclick="$('#signOutBtn').click()" class="nav-link">Logout</a>
                    <form style='display: none;' method="POST" action="{% url 'customer:logoutuser' %}">
                        {% csrf_token %}
                        <button id="signOutBtn" type="submit">Logout</button>
                    </form>
                </li>
      {% endif %}
        </ul>
  </div>
</nav>

{% block content %}{% endblock %}


<footer><div class="card">
<br>
    <div class="footer footer-expand-lg bg-primary"><center>
        <br>
	<p>Copyright © 2020 JAS Financial Services. All Rights Reserved. JAS ® is a registered trademark.</p><p>
	Managed by Jyoti Shravgi</p><p></center>
</p></div>
<style>
    .footer p{
                    color:#fff;
             }
    </style>
    </footer>

</body>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</html>

customer/templates/customer/complaint.html
{% extends "customer/base.html" %}

{% block content %}

<style>
* {
  box-sizing: border-box;
}

input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid rgb(70, 68, 68);
  border-radius: 4px;
  resize: vertical;
}
input[type=email], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid rgb(70, 68, 68);
  border-radius: 4px;
  resize: vertical;
}

label {
  padding: 12px 12px 12px 0;
  display: inline-block;
}

input[type=submit] {
  background-color: rgb(37, 116, 161);
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  float: right;
}

input[type=submit]:hover {
  background-color: #45a049;
}

.container {
  border-radius: 5px;
  background-color: #f2f2f2;
  padding: 20px;
}

.col-25 {
  float: left;
  width: 25%;
  margin-top: 6px;
}

.col-75 {
  float: left;
  width: 75%;
  margin-top: 6px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
</style>
<body>
<h2>FEED BACK FORM</h2>
<div class="container">
  <form>
    <div class="row">
      <div class="col-25">
        <label for="fname">First Name</label>
      </div>
      <div class="col-75">
        <input type="text" id="fname" name="firstname" placeholder="Your name..">
      </div>
    </div>
    <div class="row">
      <div class="col-25">
        <label for="lname">Last Name</label>
      </div>
      <div class="col-75">
        <input type="text" id="lname" name="lastname" placeholder="Your last name..">
      </div>
    </div>
    <div class="row">
        <div class="col-25">
          <label for="email">Mail Id</label>
        </div>
        <div class="col-75">
          <input type="email" id="email" name="mailid" placeholder="Your mail id..">
        </div>
      </div>
    <div class="row">
      <div class="col-25">
        <label for="country">Country</label>
      </div>
      <div class="col-75">
        <select id="country" name="country">
            <option value="none">Select Country</option>
          <option value="australia">Australia</option>
          <option value="canada">Canada</option>
          <option value="usa">USA</option>
          <option value="russia">Russia</option>
          <option value="japan">Japan</option>
          <option value="india">India</option>
          <option value="china">China</option>
        </select>
      </div>
    </div>
    <div class="row">
      <div class="col-25">
        <label for="feed_back">Feed Back</label>
      </div>
      <div class="col-75">
        <textarea id="subject" name="subject" placeholder="Write something.." style="height:200px"></textarea>
      </div>
    </div>
    <div class="row">
      <input type="submit" value="Submit">
    </div>
  </form>
</div>

</body>


{% endblock %}

customer/templates/customer/customerportal.html
{% extends "customer/base.html" %}

{% block content %}

Congratulations!!

</body>


{% endblock %}

customer/templates/customer/signupuser.html
{% extends "customer/base.html" %}

{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            <h2>Sign Up</h2>
        </div>
    </div>
    <div class="row justify-content-center mt-5">
        <div class="col-md-5">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" class="form-control" id="username" aria-describedby="usernameHelp">
                    <small id="usernameHelp" class="form-text text-muted">Your username must be unique. We'll let you know if someone has taken it already.</small>
                </div>
                 <div class="form-group">
                    <label for="email">Email Id</label>
                    <input type="email" name="email" class="form-control" id="email" aria-describedby="emailHelp">
                    <small id="emailHelp" class="form-text text-muted">We'll let you know if the email has already registered .</small>
                </div>
                <div class="form-group">
                    <label for="mob">Mobile Number</label>
                    <input type="tel" name="mob" class="form-control" id="mob" aria-describedby="mobHelp">
                    <small id="mobHelp" class="form-text text-muted">We'll let you know if the Mobile Number has already registered .</small>
                </div>
                <div class="form-group">
                    <label for="password1">Password</label>
                    <input type="password" name="password1" class="form-control" id="password1">
                </div>
                <div class="form-group">
                    <label for="password2">Confirm Password</label>
                    <input type="password" name="password2" class="form-control" id="password2">
                </div>
                <button type="submit" class="btn btn-primary">Sign Up</button>
            </form>
            <hr>
            <div class="text-center">
                Do you already have an account? <a href="{% url 'customer:loginuser' %}">Login here</a>
            </div>
        </div>
    </div>
{% endblock %}

customer/templates/customer/suggestion.html
{% extends "customer/base.html" %}

{% block content %}

<style>
* {
  box-sizing: border-box;
}

input[type=text], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid rgb(70, 68, 68);
  border-radius: 4px;
  resize: vertical;
}
input[type=email], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid rgb(70, 68, 68);
  border-radius: 4px;
  resize: vertical;
}
input[type=tel], select, textarea {
  width: 100%;
  padding: 12px;
  border: 1px solid rgb(70, 68, 68);
  border-radius: 4px;
  resize: vertical;
}

label {
  padding: 12px 12px 12px 0;
  display: inline-block;
}

input[type=submit] {
  background-color: rgb(37, 116, 161);
  color: white;
  padding: 12px 20px;
  border: none;
  border-radius: 4px;
  cursor: pointer;
  float: right;
}

input[type=submit]:hover {
  background-color: #45a049;
}

.col-25 {
  float: left;
  width: 25%;
  margin-top: 6px;
}

.col-75 {
  float: left;
  width: 75%;
  margin-top: 6px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
</style>
<body>
    <br>
<center><h3><b>Tell us your Idea</b><br></h3><h5> We can give Birth to it Together!</h5></center>
<br>
<div class="container">
  <form>
    <div class="row">
      <div class="col-25">
        <label for="fname">Full Name</label>
      </div>
      <div class="col-75">
        <input type="text" id="fname" name="firstname" placeholder="Your full name..">
      </div>
    </div>
    <div class="row">
      <div class="col-25">
        <label for="fname">Mobile Number</label>
      </div>
      <div class="col-75">
        <input type="tel" id="mob" name="mob" placeholder="Your mobile number..">
      </div>
    </div>
    <div class="row">
        <div class="col-25">
          <label for="email">Mail Id</label>
        </div>
        <div class="col-75">
          <input type="email" id="email" name="mailid" placeholder="Your mail id..">
        </div>
      </div>
    <div class="row">
      <div class="col-25">
        <label for="state">State</label>
      </div>
      <div class="col-75">
        <select id="state" name="state">
            <option value="none">Select State</option>
          <option value="australia">Maharashtra</option>
          <option value="canada">Delhi</option>
          <option value="usa">Tamil Nadu</option>
          <option value="russia">Kerala</option>
        </select>
      </div>
    </div>
    <div class="row">
      <div class="col-25">
        <label for="feed_back">Complaint</label>
      </div>
      <div class="col-75">
        <textarea id="subject" name="subject" placeholder="Write something.." style="height:200px"></textarea>
      </div>
    </div>
    <div class="row">
      <input type="submit" value="Submit">
    </div>
  </form>
</div>

</body>


{% endblock %}

home/templates/home/aboutus.html
{% extends "home/base.html" %}
{% load static %}

{% block content %}

<link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/carousel/">
<div class="marketing container" style="background-color:white;">
<div class="jumbotron" style="background-color:white;">
    <h1><center><b>ABOUT US</b></center></h1><br>
<p class="lead">JAS Services is a Property,Loan & Insurance portfolio management venture started in the year 2020. Simplifying the complexity of the client is a key objective at JAS Services.
Social responsibility
We are very much aware that this world isn't ideal and that by helping others we can make a difference. It is our goal to make a difference in this world by creating bespoke services. By becoming a part of Jas Services you will contribute too.
</p>
</div>
</div>
<div class="marketing container" style="background-color:white;">
<hr class="featurette-divider">
    <h2><center><b>WHY US</b></center></h2>
    <br>
    <div class="row featurette">

      <div class="col-md-7">
        <h2 class="featurette-heading">Our Approach.</h2>
        <p class="lead">We are very much aware that this world isn't ideal and that by helping others we can make a difference. We regularly attend humanitarian tournaments, provide gifts for various occasions to the less privileged and donate our knowledge. It is our goal to make a difference in this world by creating bespoke products and giving back. By becoming a part of EtonDigital, you will contribute too.</p>
      </div>
      <div class="col-md-4 order-md-2">
          <br>
        <img src="{% static 'home/ourapproach.jfif' %}" alt="Squirrel" width="450" height="250">
      </div>

    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading">Raising the Bar with Quality. </h2>
        <p class="lead">We are very much aware that this world isn't ideal and that by helping others we can make a difference. We regularly attend humanitarian tournaments, provide gifts for various occasions to the less privileged and donate our knowledge. It is our goal to make a difference in this world by creating bespoke products and giving back. By becoming a part of EtonDigital, you will contribute too.</p>
      </div>
      <div class="col-md-5 order-md-1">
          <br>
        <img src="{% static 'home/excellence.jfif' %}" alt="Squirrel" width="450" height="250">
      </div>
    </div>
    <br>
    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">Social Responsibility. </h2>
        <p class="lead">We are very much aware that this world isn't ideal and that by helping others we can make a difference. We regularly attend humanitarian tournaments, provide gifts for various occasions to the less privileged and donate our knowledge. It is our goal to make a difference in this world by creating bespoke products and giving back. By becoming a part of EtonDigital, you will contribute too.</p>
      </div>
      <div class="col-md-5">
          <br>
        <img src="{% static 'home/Corporate-social-responsibility.jpg' %}" alt="Squirrel" width="450" height="250">
      </div>
    </div>

    <hr class="featurette-divider">



<br>
<br>
	<p><h2><center><b>OUR PROCESS</b></center></h2>
	<br><br>
<div id="dg">
		<div class="container">
			<div class="row centered">

			<!-- First Chart -->
			<div class="col-lg-3">
            <img src="{% static 'home/progressbar.png' %}" alt="Squirrel" width="220" height="200">
				<br>
				<p><b>Identify</b></p>
				<p><small>A key step in the process - identifying the right property suited to your requirements.</small></p>
			</div><!-- /col-lg-3 -->

			<!-- Second Chart -->
			<div class="col-lg-3">
				<img src="{% static 'home/progressbar.png' %}" alt="Squirrel" width="220" height="200">
				<br>
				<p><b>Research</b></p>
				<p><small>The most important step in our process to provide you with the perfect property.</small></p>
			</div><!-- /col-lg-3 -->

			<!-- Third Chart -->
			<div class="col-lg-3">
				<img src="{% static 'home/progressbar.png' %}" alt="Squirrel" width="220" height="200">
				<br>
				<p><b>Simplify</b></p>
				<p><small>Simplifying the process to maintain transparency and understanding.</small></p>
			</div><!-- /col-lg-3 -->

			<!-- Fourth Chart -->
			<div class="col-lg-3">
<img src="{% static 'home/progressbar.png' %}" alt="Squirrel" width="220" height="200">
				<br>
				<p><b>Delivery</b></p>
				<p><small>Prompt service to ensure the timely completion of due processes to maximize comfort and benefit to customer.</small></p>
			</div><!-- /col-lg-3 -->


			</div><!-- row -->
		</div><!-- container -->
	</div>

<hr class="featurette-divider">


<style>
.image-banner {
	position: relative;
	margin-bottom: 40px;
	overflow: hidden;
}
    .image-banner text {
	display: block;
	transition: all 1.7s;
}

.image-banner:hover text {
	transform: scale(1.5);
}

.banner-description {
	position: absolute;
	bottom: 0;
	left: 0;
	color: #FFF;
	background-color: rgba(0, 0, 0, .65);
	padding: 15px 25px;
	opacity: 0;
	transition-property: all;
	transition-duration: 1s;
	transform: translateY(100%);
}

.image-banner:hover .banner-description {
	opacity: 1;
	transform: translateY(0);
}
/* Center align the text within the three columns below the carousel */
.marketing .col-lg-4 {
  margin-bottom: 1.5rem;
  text-align: center;
}
.marketing h2 {
  font-weight: 400;
}
.marketing .col-lg-4 p {
  margin-right: .75rem;
  margin-left: .75rem;
}


</style>

  <div class="album py-5 bg-light">
      <p><h2><center><b>OUR VALUES</center></h2>
      <br>
    <div class="container">
<br>
      <div class="row">
        <div class="col-md-4">
            <div class="image-banner">
                <div class="card badge-primary" style="width: 21.87rem; height: 13rem;">
                    <div class="card-body">
                        <h2 class="card-text"><br><center> Quality </center></h2>
                    </div>

				<div class="banner-description">
					<p>This is a brief description of the image. This is a photograph of a squirel on the train tracks that was taken in Oregon. This squirrel was incredibly brave and enjoyed playing on the tracks.</p>
                </div>
                </div>
			</div><!-- /image-banner -->
        </div>
        <div class="col-md-4">
            <div class="image-banner">
                <div class="card badge-success" style="width: 21.87rem; height: 13rem;">
                    <div class="card-body">
                        <h2 class="card-text"><br><center>Service</center></h2>
                    </div>
                </div>
				<div class="banner-description">
					<p>This is a brief description of the image. This is a photograph of a squirel on the train tracks that was taken in Oregon. This squirrel was incredibly brave and enjoyed playing on the tracks.</p>
                </div>
			</div><!-- /image-banner -->
        </div>
        <div class="col-md-4">
            <div class="image-banner">
                <div class="card badge-secondary" style="width: 21.87rem; height: 13rem;">
                    <div class="card-body">
                        <h2 class="card-text"><br><center>Excellence</center></h2>
                    </div>
                </div>
				<div class="banner-description">
					<p>This is a brief description of the image. This is a photograph of a squirel on the train tracks that was taken in Oregon. This squirrel was incredibly brave and enjoyed playing on the tracks.</p>
                </div>
			</div><!-- /image-banner -->
        </div>
    </div>
      <div class="row">
        <div class="col-md-4" >
            <div class="image-banner">
                <div class="card badge-dark" style="width: 21.87rem; height: 13rem;">
                    <div class="card-body">
                        <h2 class="card-text"><br><center>Passion</center></h2>
                    </div>
                </div>
				<div class="banner-description">
					<p>This is a brief description of the image. This is a photograph of a squirel on the train tracks that was taken in Oregon. This squirrel was incredibly brave and enjoyed playing on the tracks.</p>
                </div>
			</div><!-- /image-banner -->
        </div>
        <div class="col-md-4">
             <div class="image-banner">
                <div class="card badge-light" style="width: 21.87rem; height: 13rem;">
                    <div class="card-body">
                        <h2 class="card-text"><br><center>Integrity</center></h2>
                    </div>
                </div>
				<div class="banner-description">
					<p>This is a brief description of the image. This is a photograph of a squirel on the train tracks that was taken in Oregon. This squirrel was incredibly brave and enjoyed playing on the tracks.</p>
                </div>
			</div><!-- /image-banner -->
        </div>
                <div class="col-md-4">
             <div class="image-banner">
                <div class="card  badge-info" style="width: 21.87rem; height: 13rem;">
                    <div class="card-body">
                        <h2 class="card-text"><br><center>Flexibility</center></h2>
                    </div>
                </div>
				<div class="banner-description">
					<p>This is a brief description of the image. This is a photograph of a squirel on the train tracks that was taken in Oregon. This squirrel was incredibly brave and enjoyed playing on the tracks.</p>
                </div>
			</div><!-- /image-banner -->
        </div>
     </div>
     </div>
</div>
</div>

{% endblock %}

home/templates/home/loan.html
{% extends "home/base.html" %}
{% load static %}

{% block content %}
<div class="jumbotron" style="background-color:white;">
<div class="card-deck">
    <div class="card" style="width: 10rem;">
        <img src="{% static 'home/Insurance.jpg' %}" class="card-img-top" alt="pic">
        <div class="card-body">
            <h5 class="card-title">Home Loan</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <a href="#" class="btn btn-primary">Details</a>
        </div>
    </div>
    <div class="card" style="width: 10rem;">
        <img src="{% static 'home/loans.jpg' %}" class="card-img-top" alt="pic">
        <div class="card-body">
            <h5 class="card-title">Business Loan</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <a href="#" class="btn btn-primary">Details</a>
        </div>
    </div>
    <div class="card" style="width: 10rem;">
        <img src="{% static 'home/property.jpg' %}" class="card-img-top" alt="pic">
        <div class="card-body">
          <h5 class="card-title">Vehicle Loan</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <a href="#" class="btn btn-primary">Details</a>
        </div>
    </div>
</div>
</div>
{% endblock %}

home/templates/home/sendemail.html
{% extends "home/base.html" %}
{% load static %}

{% block content %}
Email Sent

{% endblock %}